### ISSUE TITLE
Radio flashing issues

### ISSUE THREAD

**Issue by elodotwe** [FRC5263/2018Robot#14]
Cannot get radio to work with wireless.

On Swag PC, updated to 2018 radio configurator.
Ran it, selected Ethernet from list of interfaces.
Clicked "Load firmware" and got the error
```
2018-01-20 12:27:14,595 ERROR [SwingWorker-pool-2-thread-1] f.RadioFirmwareLoadSequence [RadioFirmwareLoadSequence.java:221] Bridge firmware sequence failed: Error finding NPF device name for adapter: Broadcom NetXtreme 57xx Gigabit Controller
Try disabling all other adapters (using the Control Panel)
frcradiokiosk.RadioException: Error finding NPF device name for adapter: Broadcom NetXtreme 57xx Gigabit Controller
Try disabling all other adapters (using the Control Panel)
	at frcradiokiosk.openMesh.OM5P_AN.prepareLoadFirmware(OM5P_AN.java:334) ~[FRCWpaKiosk.jar:1.3.18.554]
	at frcradiokiosk.RadioFirmwareLoadSequence.program(RadioFirmwareLoadSequence.java:174) [FRCWpaKiosk.jar:1.3.18.554]
	at frcradiokiosk.RadioFirmwareLoadSequence.doInBackground(RadioFirmwareLoadSequence.java:144) [FRCWpaKiosk.jar:1.3.18.554]
	at frcradiokiosk.RadioFirmwareLoadSequence$1.doInBackground(RadioFirmwareLoadSequence.java:41) [FRCWpaKiosk.jar:1.3.18.554]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_71]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
```

**Comment by elodotwe** [comment]
I got around the NPF error by disabling all network interfaces on Swag PC except the Ethernet interface.

Plugged ethernet into the af port on the radio.
Ran the radio config tool, clicked "load firmware" and power cycled the radio.
Radio was found--configuration tool downloaded firmware and finished.
Specified team number and name, clicked Configure.
The configuration completed in about a minute.
Power cycled the radio, and now it appears to be broadcasting Wifi.

I did this for both radios we had on the practice bot. The one that's plugged into the practice bot still should be 5263_pro, and the one sitting next to Swag PC is set to just 5263. Neither should require a password.
